### ISSUE TITLE
A tiny harmless error in the about section :)

### ISSUE THREAD

**Issue by Jackie7610** [the-weird-aquarian/IYPS#3]
**Describe the bug**
The version number in the about section is incorrect.
_Current app version: 1.0.1_
_Error: 1.0.0_

**To Reproduce**
1. Open the app and tap on the three dotted menu
2. Tap on ‘about’
3. See error (app version)

Thanks

**Comment by the-weird-aquarian** [comment]
Yes I became aware about that after releasing the current version and it has already been fixed. Changes will be reflected in next release. :)
