### ISSUE TITLE
Incorrect translation in french

### ISSUE THREAD

**Issue by Amiralgaby** [the-weird-aquarian/IYPS#9]
**Describe the bug**

Bad french translation

**To Reproduce**
  * take a password who has 2 months to crack, displayed "2 moiss" but it must be "2 mois"
  * The label "weak" must be translated by "faible"
  * Bad word "fissuré" is nos used to say crack a password, the word must be "cassé" (or "cracké" it's also used commonly but I don't know if it's from french dictionnary)
 
**Expected behavior**
correct french translation

**Additional context**

I'm french so I know what it's must be displayed ;)

**Comment by the-weird-aquarian** [comment]
PR merged.
